spring:
  jackson:
    time-zone: Europe/Moscow
    date-format: yyyy-MM-dd HH:mm:ss Z
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
  messages:
    encoding: UTF-8
    basename: i18n/messages
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    root: info