CREATE SEQUENCE AUTHORS_S INCREMENT BY 1 MINVALUE 1 NO CACHE;

CREATE SEQUENCE GENRES_S INCREMENT BY 1 MINVALUE 1 NO CACHE;

CREATE SEQUENCE BOOKS_S INCREMENT BY 1 MINVALUE 1 NO CACHE;

CREATE SEQUENCE BOOK_COMMENTS_S INCREMENT BY 1 MINVALUE 1 NO CACHE;

CREATE SEQUENCE USERS_S INCREMENT BY 1 MINVALUE 1 NO CACHE;

CREATE SEQUENCE AUTHORITIES_S INCREMENT BY 1 MINVALUE 1 NO CACHE;

CREATE TABLE IF NOT EXISTS AUTHORS
(
    AUTHOR_ID BIGINT        NOT NULL DEFAULT AUTHORS_S.NEXTVAL PRIMARY KEY,
    NAME      VARCHAR2(255) NOT NULL,
    SURNAME   VARCHAR2(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_ID BIGINT               NOT NULL DEFAULT GENRES_S.NEXTVAL PRIMARY KEY,
    NAME     VARCHAR2(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOKS
(
    BOOK_ID          BIGINT               NOT NULL DEFAULT BOOKS_S.NEXTVAL PRIMARY KEY,
    AUTHOR_ID        BIGINT               NOT NULL,
    GENRE_ID         BIGINT               NOT NULL,
    NAME             VARCHAR2(255) UNIQUE NOT NULL,
    PUBLICATION_DATE DATE                 NOT NULL,
    PRINT_LENGTH     INT                  NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (AUTHOR_ID) ON DELETE CASCADE,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (GENRE_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOOKS_COMMENTS
(
    COMMENT_ID BIGINT        NOT NULL DEFAULT BOOK_COMMENTS_S.NEXTVAL PRIMARY KEY,
    BOOK_ID    BIGINT        NOT NULL,
    TEXT       VARCHAR2(255) NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID                 BIGINT        NOT NULL DEFAULT USERS_S.NEXTVAL PRIMARY KEY,
    USERNAME                VARCHAR2(255) NOT NULL UNIQUE,
    PASSWORD                VARCHAR2(255) NOT NULL,
    ACCOUNT_NON_EXPIRED     BOOLEAN       NOT NULL,
    ACCOUNT_NON_LOCKED      BOOLEAN       NOT NULL,
    CREDENTIALS_NON_EXPIRED BOOLEAN       NOT NULL,
    ENABLED                 BOOLEAN       NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES
(
    AUTHORITY_ID BIGINT        NOT NULL DEFAULT AUTHORITIES_S.NEXTVAL PRIMARY KEY,
    AUTHORITY    VARCHAR2(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_AUTHORITIES
(
    USER_ID      BIGINT NOT NULL,
    AUTHORITY_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITIES (AUTHORITY_ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, AUTHORITY_ID)
);
