spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: schema.sql
    data: data.sql
  messages:
    encoding: UTF-8
    basename: i18n/messages
application:
  locale: en