CREATE TABLE IF NOT EXISTS AUTHORS
(
    AUTHOR_ID BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR2(100) NOT NULL,
    SURNAME   VARCHAR2(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_ID BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR2(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS BOOKS
(
    BOOK_ID          BIGINT        NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_ID        BIGINT        NOT NULL,
    GENRE_ID         BIGINT        NOT NULL,
    NAME             VARCHAR2(150) NOT NULL,
    PUBLICATION_DATE DATE          NOT NULL,
    PRINT_LENGTH     INT           NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (AUTHOR_ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (GENRE_ID)
);
